### ISSUE TITLE
Variety/cultuvar

### ISSUE THREAD

**Issue by KitWallace** [KitWallace/treemap#10]
variety/cultivar according to https://en.wikipedia.org/wiki/Wikipedia:Naming_conventions_(flora)
variety should be preceeded by 'var'  eg 
Populus nigra var italica
cultivar single quoted  e.g. 
Fraxinus excelsior 'Pendula'

but 	
Fagus sylvatica pendula
is a cultivar
in the data these forms appear but most are of the form eg
Cornus controversa variegata  
which seems to be a cultivar

**Comment by MarkCDAshdown** [comment]
OK - all done, I think. M
