### ISSUE TITLE
Common name

### ISSUE THREAD

**Issue by KitWallace** [KitWallace/treemap#11]
In the data, this is typically shown in the indexable form,

eg Oak, Turkey 
rather than Turkey Oak

I've used the supplied name in lists but in expanded entries Ive reversed the name to its normal form

There are some common names which are inconsistantly in the normal form already and should be changed

The reversed parts to get the normal form fails in a few cases eg  
Ash, Manna or Flowering Ash
 I could split the name on or to add an alternate name

**Comment by KitWallace** [comment]
altname added

**Comment by KitWallace** [comment]
suggest that text be edited to use only the common name - conversion to lastname , rest form can be cretead in the script

**Comment by MarkCDAshdown** [comment]
OK all common names standardised as discussed. M

**Comment by KitWallace** [comment]
Conversion to lexographic form is not quite as simple as puting the last word first but handable with special cases
