### ISSUE TITLE
compute any boundary area

### ISSUE THREAD

**Issue by MarkCDAshdown** [KitWallace/treemap#118]
Compute the boundary area given the polygon(s) which define it

**Comment by KitWallace** [comment]
Found algorithm - bit slow and I need to validate it against some boundary with a known area -

**Comment by KitWallace** [comment]
Testing on a known area shows that it works and when tested on wards which probably changed little in the reorganisation it seems ok.  Bishopston and Ashley Down have an area of 153 hectares

**Comment by KitWallace** [comment]
Ward areas now cached - utility program can cache others as required - added into site-page
