### ISSUE TITLE
Fix the disparity between Ward Site categories tree counts and the tree count at the Ward level

### ISSUE THREAD

**Issue by MarkCDAshdown** [KitWallace/treemap#127]

**Comment by KitWallace** [comment]
Sorry can you eluciate?

**Comment by MarkCDAshdown** [comment]
Look at the tree count in the list of wards then open each ward And note a different tree count number at that level

**Comment by MarkCDAshdown** [comment]
CW - thinks this is because one view includes stumps etc and the other does not.

**Comment by KitWallace** [comment]
suspect a caching problem - now have recaching script in admin
