### ISSUE TITLE
Link to complete BCC Tree dataset (.csv or live?)

### ISSUE THREAD

**Issue by MarkCDAshdown** [KitWallace/treemap#26]
Allow user to filter results by SITE_NAME a filtered drop-down or freetext search
Report also Crown Height & Crown Width

**Comment by MarkCDAshdown** [comment]
Reference the base dataset maintained by BCC on the web site.

**Comment by KitWallace** [comment]
Link added to About
Width and height now parsed 
names qualified by Unidentified etc reduced to name only

**Comment by MarkCDAshdown** [comment]
Oh, That reminds me, I stripped all the 'unknown' instances etc out of the .csv file for Ashton Court and Bradon Hill. In the shared folder.

**Comment by KitWallace** [comment]
Still worth doing in the parser since moding the CSV would be a pain if other BCC sets are to be imported

**Comment by MarkCDAshdown** [comment]
Agreed.

**Comment by KitWallace** [comment]
link in Links
