### ISSUE TITLE
Trees of Bristol - Bug Issue

### ISSUE THREAD

**Issue by MarkCDAshdown** [KitWallace/treemap#40]
Open the Stumps Collection
sort by Id
Select either of the top two stumps listed - with no OBJECTID No. listed
The Search page is displayed - the stump page cannot be opened

**Comment by KitWallace** [comment]
these entries come from these rows in the csv data - which I should have
rejected

,,"Gatton Road, St Werburghs",,,"Gatton Road, St Werburghs",Stump on
,,,,,,,,,"( 51.467971, -2.571564)",ZZ Tree stump,Stump,,,
,,"Gatton Road, St Werburghs",,,"Gatton Road, St Werburghs",Stump on
,,,,,,,,,"( 51.467987,  -2.571505)",ZZ Tree stump,Stump,,,

Ids are constructed from the ASSET_ID

C

**Comment by MarkCDAshdown** [comment]
Yes - these are two stumps which I spotted the other day which are not shown on the BCC stump asset list - so I added them manually - hence no ASSET_ID.

**Comment by KitWallace** [comment]
so do you want to assign ASSET_IDs from your own sequence?

**Comment by MarkCDAshdown** [comment]
Not sure I follow?  I suppose we could just increment the last ASSET_ID - but then there is a risk of duplication at a later date?

Fancy to coffee to discuss where we are?

**Comment by KitWallace** [comment]
I was thinking that you could have a sequence of ASSET_IDs   say X001 X002 .. which will not conflict with a BCC all digit asset nos.

**Comment by MarkCDAshdown** [comment]
OK. I have updated BCC Stump GE Stump Survey.csv as suggested in the shared folder

**Comment by KitWallace** [comment]
New version uploaded and added stumps parsed
